name: Publish

on:
  push:
    branches:
      - master
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: npm ci

      - name: Check format (prettier)
        run: npm run format-check

      - name: Lint (eslint)
        run: npm run lint-check

      - name: Publish docker image
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          NEXT_PUBLIC_BUILD_TIME_COURSE_LIMIT: ${{ secrets.NEXT_PUBLIC_BUILD_TIME_COURSE_LIMIT }}
          NEXT_PUBLIC_GRADES_API_URL: ${{ secrets.NEXT_PUBLIC_GRADES_API_URL }}
          NEXT_PUBLIC_SENTRY_DSN: ${{ secrets.NEXT_PUBLIC_SENTRY_DSN }}
          NEXT_PUBLIC_GA_TRACKING_ID: ${{ secrets.NEXT_PUBLIC_GA_TRACKING_ID }}
          NEXT_PUBLIC_FEIDE_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_FEIDE_CLIENT_ID }}
          NEXT_PRIVATE_FEIDE_CLIENT_SECRET: ${{ secrets.NEXT_PRIVATE_FEIDE_CLIENT_SECRET }}
          NEXT_PUBLIC_FEIDE_AUTH_ENDPOINT: ${{ secrets.NEXT_PUBLIC_FEIDE_AUTH_ENDPOINT }}
          NEXT_PRIVATE_SESSION_SECRET: ${{ secrets.NEXT_PRIVATE_SESSION_SECRET }}
        with:
          name: gradestats-app
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: registry.online.ntnu.no
          tag_semver: true
          buildargs: NEXT_PUBLIC_BUILD_TIME_COURSE_LIMIT,NEXT_PUBLIC_GRADES_API_URL,NEXT_PUBLIC_SENTRY_DSN,NEXT_PUBLIC_GA_TRACKING_ID,NEXT_PUBLIC_CANONICAL_URL,NEXT_PUBLIC_FEIDE_CLIENT_ID,NEXT_PRIVATE_FEIDE_CLIENT_SECRET,NEXT_PUBLIC_FEIDE_AUTH_ENDPOINT,NEXT_PRIVATE_SESSION_SECRET
