name: Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: yarn

      - name: Check format (prettier)
        run: yarn format-check

      - name: Lint (eslint)
        run: yarn lint-check

      - name: Publish docker image
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID }}
        with:
          name: gradestats-app
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: registry.online.ntnu.no
          tag_names: true
          buildargs: SENTRY_DSN,GA_TRACKING_ID
