name: Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: yarn

      - name: Check format (prettier)
        run: yarn format-check

      - name: Lint (eslint)
        run: yarn lint-check

      - name: Compile
        run: yarn build

      - name: Test
        run: yarn test

      - name: Publish docker image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: gradestats-app
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: registry.online.ntnu.no
          tag_names: true
