name: Pull Request

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: yarn

      - name: Check format (prettier)
        run: yarn format-check

      - name: Lint (eslint)
        run: yarn lint-check

      - name: Compile
        run: yarn build

      - name: Test
        run: yarn test
