name: Pull Request

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: npm ci

      - name: Check format (prettier)
        run: npm run format-check

      - name: Lint (eslint)
        run: npm run lint-check

      - name: Typescript Compile
        run: yarn tsc

      - name: Compile
        run: npm run build
