name: Pull Request

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version-file: 'package.json'

      - name: Install dependencies
        run: npm ci

      - name: Check format (prettier)
        run: npm run format-check

      - name: Lint (eslint)
        run: npm run lint-check

      - name: Typescript Compile
        run: npm run tsc

      - name: Compile
        run: npm run build

      - name: Lighthouse
        run: npm run lighthouse
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
